### PR TITLE
fix(windows): auto-detect pwsh/powershell (Fixes #301)

### LINKED ISSUE #301: bug: "no such file or directory: 'pwsh'" on Windows
### Did you read the documentation and check existing issues?

- [x] I have read all the documentations ([README](https://github.com/brianhuster/live-preview.nvim), [`:h livepreview`](https://github.com/brianhuster/live-preview.nvim/blob/main/doc/livepreview.txt), [Wiki](https://github.com/brianhuster/live-preview.nvim/wiki))
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the [existing issues](https://github.com/brianhuster/live-preview.nvim/issues) and [closed issues](https://github.com/brianhuster/live-preview.nvim/issues?q=is%3Aissue+is%3Aclosed) issues

### Neovim version (nvim -v)

0.11.1

### Operating system/version

Windows 10

### Browser/version

Librewolf

### Describe the bug

When I try to run `:LivePreview start` in my terminal, I get the error:

```

Error executing Lua callback: ...gram Files\Neovim\share\nvim\runtime/lua/vim/_system.lua:248: ENOENT: no such file or directory: "pwsh"
stack traceback:
	[C]: in function 'error'
	...gram Files\Neovim\share\nvim\runtime/lua/vim/_system.lua:248: in function 'spawn'
	...gram Files\Neovim\share\nvim\runtime/lua/vim/_system.lua:353: in function 'system'
	...nvim\plugged\live-preview.nvim/lua/livepreview/utils.lua:163: in function 'await_term_cmd'
	...nvim\plugged\live-preview.nvim/lua/livepreview/utils.lua:291: in function 'processes_listening_on_port'
	...\nvim\plugged\live-preview.nvim/lua/livepreview/init.lua:33: in function 'start'
	...al\nvim\plugged\live-preview.nvim\plugin\livepreview.lua:57: in function <...al\nvim\plugged\live-preview.nvim\plugin\livepreview.lua:28>

```

`pwsh` isn't a valid command to launch powershell on Windows 10 unles the user sets up an alias, as I found out to my dismay a while ago, 😄 . While the `pwsh` alias I do have works in my terminal to launch a new powershell instance, I guess it's not compatible with the plugin's process. Likely, it's just a simple fix to swap the references in the source code to `powershell` instead.

I have no configuration set, and saw no option to set the shell command, but perhaps there could be?

### Steps To Reproduce

1. Clone the plugin `git clone https://github.com/brianhuster/live-preview.nvim`
2. Open Nvim with minimal repro file `nvim -u minimal_init.lua`
3. ...

### Expected Behavior

The command `LivePreview start` to open the server.

### Health

```help
==============================================================================
livepreview:                             require("livepreview.health").check()

Check dependencies ~
- ✅ OK Nvim 0.11.1 is compatible with Live Preview
- ✅ OK `powershell` is available
- ⚠️ WARNING `mini.pick` (optional) is not installed
- ✅ OK `telescope` is installed
- ⚠️ WARNING `fzf-lua` (optional) is not installed

Checkhealth server and process ~
- ✅ OK This Nvim process's PID is 3808
- ❌ ERROR Failed to run healthcheck for "livepreview" plugin. Exception:
  ...gram Files\Neovim\share\nvim\runtime/lua/vim/_system.lua:248: ENOENT: no such file or directory: "pwsh"
```

### Minimal config to reproduce

```lua
vim.cmd.set "rtp+=/path/to/live-preview.nvim"

require("livepreview.config").set {
  --- Configuration here
}
```

### PR DESCRIPTION
**Pull request by sarahyack**
## Issue

The default shell command selection for windows was simply `"pwsh"`, as this is only applicable for Powershell Core (6/7) shipped with Windows 11, it is not applicable for Windows 10, as it usually ships with Powershell 5.1, which does not have the `pwsh` command built-in, and instead launches with the command `powershell`.

**Fixes #301**

## Fix

Changed the windows shell selection part of `utils.term_cmd` & `utils.await_term_cmd` to use a new picker function `pick_powershell()`, that determines which command vim detects is available with `vim.fn.executable()`, with a preference towards the newer `pwsh`, and a fallback to `powershell`.

## Testing

I do not have a Windows 11 machine or VM, so only tested on a Windows 10 machine, but the error mentioned in #301 no longer occurs with the new changes, and `:LivePreview start` works as expected. No changes to previous functionality for windows users should occur besides adding support for Windows 10, thus I expect everything should work fine on a Windows 11 machine.

*Happy to tweak based on feedback!*

### CODE REVIEW

File: lua/livepreview/utils.lua [hunk 1]
```diff
@@ -125,6 +125,21 @@ function M.isWindows()
...
+--- every Windows 10/11 install).
+---
+---@return string: `"pwsh"` if available, otherwise `"powershell"`.
+local function pick_powershell()
+	if vim.fn.executable("pwsh") == 1 then
+		return "pwsh"
+	elseif vim.fn.executable("powershell") == 1 then
+		return "powershell"
+	end
+end
```
Comment (brianhuster) [inline lua/livepreview/utils.lua:141]: Should cache the result

Comment (sarahyack) [reply lua/livepreview/utils.lua:141]: Alright, I'll get that done tomorrow!

**Comment by sarahyack** [comment]
Please take a look and let me know if there are any more issues!

**Comment by sarahyack** [comment]
**Heads Up (Unrelated to this Fix):**

While testing, I noticed that the plugin was failing to initialize a server for a HTML file I was trying to open. I had previously with the initial tests opened a Markdown file and not an HTML file, so I have no context in regards to whether it was broken then too, but as of right now the server is failing to start for HTML files. It will, however start for a Markdown file, though it only works the first time you open the server, after which even if you kill the port connection (whether using built-in `:LivePreview close` or using PowerShell), it will still initialize the process, but it'll get stuck in an endless loading loop. Errors suggest that it is unable to overwrite the port instance as it is "read-only or constant" in the case of the Markdown issue, and that when trying to preview a HTML file the value of `server` is nil. I've determined that I did not introduce these issues, and I've checked compatibility for what PowerShell commands I could find to make sure it's compatible with PowerShell 5.1 as well, and there are no issues in that regard.

Let me know if you would like me to file bug reports related to the issues outlined above, and I'd be happy to oblige! Please note, however, the scope of these issues falls outside of my experience, and I would be unlikely to be able to resolve them.

File: lua/livepreview/utils.lua [hunk 2]
```diff
@@ -125,19 +125,28 @@ function M.isWindows()
 	return vim.uv.os_uname().version:match("Windows")
 end
 
+---@type string|nil
+local powershell_command
```
Comment (brianhuster) [inline lua/livepreview/utils.lua:129]: Should be
```lua
---@type 'pwsh'|'powershell'|nil
```

File: lua/livepreview/utils.lua (hunk 1 above)
Comment (brianhuster) [reply lua/livepreview/utils.lua:150]: Sorry, by caching, I mean you don't need to make it a function. Just something like
```lua
local pwsh_cmd = vim.fn.executable 'pwsh' = 1 and 'pwsh' or 
    (vim.fn.executable 'powershell' = 1 and 'powershell' or nil)

**Comment by brianhuster** [comment]
Yes, you can open a bug report with reproduce steps

File: lua/livepreview/utils.lua (hunk 1 above)
Comment (sarahyack) [reply lua/livepreview/utils.lua]: Understood, updated it!

**Comment by sarahyack** [comment]
Does anything require change for this PR?

File: lua/livepreview/utils.lua [hunk 3]
```diff
@@ -125,6 +125,11 @@ function M.isWindows()
 	return vim.uv.os_uname().version:match("Windows")
 end
 
+---@type 'pwsh'|'powershell'
+local powershell_cmd = (vim.fn.executable("pwsh") == 1 and "pwsh") 
+	or (vim.fn.executable("powershell") == 1 and "powershell") 
+	or "powershell"
```
Comment (brianhuster) [inline lua/livepreview/utils.lua:131]: Does it mean you want `powershell_cmd` to be `"powershell"` even when `vim.fn.executable('powershell') == 0`?

Comment (sarahyack) [reply lua/livepreview/utils.lua:131]: It's a last ditch resort that should never be required, since at least PowerShell 5 should be installed on any Windows Machine. It's technically not necessary, but it makes more sense as a fallback instead of "pwsh" as PowerShell Core (6/7) might not be installed on the target Windows Machine. However, I could simply remove it if you like, or change it to pass nil. That would instead throw a system error, probably, or I could implement some sort of error notification?

Comment (brianhuster) [reply lua/livepreview/utils.lua:131]: Then I don't understand why line 130 is necessary

Comment (sarahyack) [reply lua/livepreview/utils.lua:130]: > Then I don't understand why line 130 is necessary

On further thought, I don't think it is. I've updated the process.

**Comment by brianhuster** [comment]
Can you please rebase it?

**Comment by sarahyack** [comment]
> Can you please rebase it?

Never used `rebase` before, so not sure exactly how well I did, but is that satisfactory?

**Comment by brianhuster** [comment]
No  I make your PR contains only 1 commit

**Comment by sarahyack** [comment]
> No, I mean you should make your PR contains only 1 commit

Why not squash & merge? I'm not sure how I could do that. I could simply erase the history, I suppose and rebase to the beginning, but wouldn't a squash make more sense?

**Comment by brianhuster** [comment]
Yes, I mean squash

**Comment by sarahyack** [comment]
> Yes, I mean squash

That's as good as I can get. I tried to rebase it to the first commit hash in the `git log`, but it still says 4 commits. I thought the squash happens when the merge is accepted, and done as a "Squash & merge"? My git knowledge is limited, and I'm not entirely sure what else I can do to "squash".

**Comment by brianhuster** [comment]
Use command `git rebase -i HEAD~4`

**Comment by sarahyack** [comment]
> Use command `git rebase -i HEAD~4`

Thank you, how's that?
